language: android
script: "./gradlew assembleDebug"

jdk:
  - oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.3
    # The SDK version used to compile your project
    - android-23
    - extra-android-m2repository
    - extra-android-support
    # Additional components
    #- extra-android-m2repository
  licenses:
    - android-sdk-license-.+
